---
name: Deploy to GOV.UK PaaS

on:
  push:
    branches:
      - main

jobs:
  turnstyle:
    name: Wait for previous deploys to finish
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - uses: softprops/turnstyle@v1
        name: Check workflow concurrency
        with:
          poll-interval-seconds: 20
          same-branch-only: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    name: Deploy to GOV.UK PaaS
    needs: turnstyle
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: DfE-Digital/keyvault-yaml-secret@v1
        id:  keyvault-yaml-secret
        with:
          keyvault: s146d01-kv
          secret: INFRA-KEYS
          key: PAAS-USERNAME,PAAS-PASSWORD

      - uses: DFE-Digital/github-actions/setup-cf-cli@master
        with:
          CF_USERNAME: ${{ steps.keyvault-yaml-secret.outputs.PAAS-USERNAME }}
          CF_PASSWORD: ${{ steps.keyvault-yaml-secret.outputs.PAAS-PASSWORD }}
          CF_SPACE_NAME: get-into-teaching

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run-script build

      - name: Push site
        run: cf push
